#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

// --- HELPERS ---
#define _____ KC_NO
#define __v__ KC_TRNS
// --- END OF HELPERS ---

// --- LAYERS ---
#define _WORKMAN_LAYER 0
#define _QWERTY_LAYER  1
#define _MOVE_LAYER 2
#define
// --- END OF LAYERS ---

// --- TAP DANCES ---
enum {
    TD_5_F5,
};

qk_tap_dance_action_t tap_dance_actions[] = {
    [TD_5_F5] = ACTION_TAP_DANCE_DOUBLE(KC_5, KC_F5),
};
// --- END OF TAP DANCES ---

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[_WORKMAN_LAYER] = LAYOUT_ortho_5x15(
        	// -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        	MO(15)        , /* | */ KC_1   , KC_2    ,  KC_3   ,  KC_4 , TD(TD_5_F5)  , /* | */ _____, MO(15), _____, /* | */ KC_6           , KC_7  , KC_8   , KC_9    , KC_0     , /* | */ KC_BSPC     ,
        	// -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        	KC_TAB        , /* | */ KC_Q   , KC_D    , KC_R    , KC_W  , KC_B         , /* | */ _____, _____ , _____, /* | */ KC_J           , KC_F  , KC_U   , KC_P    , KC_SCLN  , /* | */ KC_QUOT     ,
        	LCTL_T(KC_ESC), /* | */ KC_A   , KC_S    , KC_H    , KC_T  , KC_G         , /* | */ _____, _____ , _____, /* | */ KC_Y           , KC_N  , KC_E   , KC_O    , KC_I     , /* | */ KC_ENT      ,
        	KC_LSFT       , /* | */ KC_Z   , KC_X    , KC_M    , KC_C  , KC_V         , /* | */ _____, _____ , _____, /* | */ KC_K           , KC_L  , OSL(5) , KC_DOT  , KC_SLSH  , /* | */ KC_RSFT     ,
        	// -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        	_____         , /* | */ KC_LGUI, KC_LCALT, KC_BSPC , KC_SPC, _____        , /* | */ _____, _____ , _____, /* | */ MO(_MOVE_LAYER), KC_ENT, _____  , KC_RALT , KC_RGUI  , /* | */ _____)      ,
        	// -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

	[_QWERTY_LAYER] = LAYOUT_ortho_5x15(
        	// ---------------------------------------------------------------------------------------------------------------------------------------------------------------
        	__v__         , /* | */ __v__   , __v__    ,  __v__   ,  __v__ , __v__         , /* | */ __v__, __v__ , __v__, /* | */ __v__           , __v__  , __v__   , __v__    , __v__     , /* | */ __v__       ,
        	// ---------------------------------------------------------------------------------------------------------------------------------------------------------------
        	__v__         , /* | */ KC_Q    , KC_W     , KC_E     , KC_R   , KC_T          , /* | */ __v__, __v__ , __v__, /* | */ KC_Y            , KC_U   , KC_I    , KC_O     , KC_P      , /* | */ __v__       ,
        	__v__         , /* | */ KC_A    , KC_S     , KC_D     , KC_F   , KC_G          , /* | */ __v__, __v__ , __v__, /* | */ KC_H            , KC_J   , KC_K    , KC_L     , __v__     , /* | */ __v__       ,
        	__v__         , /* | */ KC_Z    , KC_X     , KC_C     , KC_V   , KC_B          , /* | */ __v__, __v__ , __v__, /* | */ KC_N            , KC_M   , __v__   , __v__    , __v__     , /* | */ __v__       ,
        	// ---------------------------------------------------------------------------------------------------------------------------------------------------------------
        	__v__         , /* | */ __v__   , __v__    , __v__    , __v__  , __v__         , /* | */ __v__, __v__ , __v__, /* | */ __v__           , __v__  , __v__   , __v__    , __v__     , /* | */ __v__)      ,
        	// ---------------------------------------------------------------------------------------------------------------------------------------------------------------

	[_MOVE_LAYER] = LAYOUT_ortho_5x15(
        	// ---------------------------------------------------------------------------------------------------------------------------------------------------------------
        	__v__         , /* | */ __v__   , __v__    ,  __v__   ,  __v__ , __v__         , /* | */ __v__, __v__ , __v__, /* | */ __v__           , __v__  , __v__   , __v__    , __v__     , /* | */ __v__       ,
        	// ---------------------------------------------------------------------------------------------------------------------------------------------------------------
        	__v__         , /* | */ __v__   , __v__    , __v__    , __v__  , __v__         , /* | */ __v__, __v__ , __v__, /* | */ __v__           , __v__  , KC_UP   , __v__    , __v__     , /* | */ __v__       ,
        	__v__         , /* | */ __v__   , __v__    , __v__    , __v__  , __v__         , /* | */ __v__, __v__ , __v__, /* | */ __v__           , KC_LEFT  , KC_DOWN   , KC_RIGHT    , __v__     , /* | */ __v__       ,
        	__v__         , /* | */ __v__   , __v__    , __v__    , __v__  , __v__         , /* | */ __v__, __v__ , __v__, /* | */ __v__           , __v__  , __v__   , __v__    , __v__     , /* | */ __v__       ,
        	// ---------------------------------------------------------------------------------------------------------------------------------------------------------------
        	__v__         , /* | */ __v__   , __v__    , __v__    , __v__  , __v__         , /* | */ __v__, __v__ , __v__, /* | */ __v__           , __v__  , __v__   , __v__    , __v__     , /* | */ __v__)      ,
        	// ---------------------------------------------------------------------------------------------------------------------------------------------------------------


	[_EMPTY_LAYER] = LAYOUT_ortho_5x15(
	// ---------------------------------------------------------------------------------------------------------------------------------------------------------------
	__v__         , /* | */ __v__   , __v__    ,  __v__   ,  __v__ , __v__         , /* | */ __v__, __v__ , __v__, /* | */ __v__           , __v__  , __v__   , __v__    , __v__     , /* | */ __v__       ,
	// ---------------------------------------------------------------------------------------------------------------------------------------------------------------
	__v__         , /* | */ __v__   , __v__    , __v__    , __v__  , __v__         , /* | */ __v__, __v__ , __v__, /* | */ __v__           , __v__  , __v__   , __v__    , __v__     , /* | */ __v__       ,
	__v__         , /* | */ __v__   , __v__    , __v__    , __v__  , __v__         , /* | */ __v__, __v__ , __v__, /* | */ __v__           , __v__  , __v__   , __v__    , __v__     , /* | */ __v__       ,
	__v__         , /* | */ __v__   , __v__    , __v__    , __v__  , __v__         , /* | */ __v__, __v__ , __v__, /* | */ __v__           , __v__  , __v__   , __v__    , __v__     , /* | */ __v__       ,
	// ---------------------------------------------------------------------------------------------------------------------------------------------------------------
	__v__         , /* | */ __v__   , __v__    , __v__    , __v__  , __v__         , /* | */ __v__, __v__ , __v__, /* | */ __v__           , __v__  , __v__   , __v__    , __v__     , /* | */ __v__)      ,
	// ---------------------------------------------------------------------------------------------------------------------------------------------------------------



	[1] = LAYOUT_ortho_5x15(KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_NLCK, KC_TRNS, KC_ASTR, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_MSEL, KC_CALC, KC_MYCM, KC_MAIL, RGB_HUD, RGB_HUI, KC_P7, KC_P8, KC_P9, KC_MINS, KC_TRNS, KC_TRNS, KC_PSCR, KC_SLCK, KC_PAUS, KC_MPRV, KC_MPLY, KC_MNXT, KC_MSTP, RGB_SAD, RGB_SAI, KC_P4, KC_P5, KC_P6, KC_PLUS, KC_TRNS, RESET, KC_TRNS, KC_TRNS, DF(0), KC_VOLD, KC_MUTE, KC_VOLU, KC_APP, RGB_VAD, RGB_VAI, KC_P1, KC_P2, KC_P3, KC_PENT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, DF(2), KC_TRNS, KC_TRNS, RGB_TOG, MO(1), RGB_RMOD, RGB_MOD, KC_P0, KC_TRNS, KC_PDOT, KC_TRNS, KC_TRNS, MO(1), KC_TRNS, KC_TRNS, DF(4)),
	[2] = LAYOUT_ortho_5x15(KC_NO, KC_NO, KC_W, KC_E, KC_NO, KC_NO, KC_NO, MO(15), KC_NO, KC_NO, KC_NO, KC_I, KC_O, KC_NO, KC_NO, KC_TAB, KC_Q, KC_S, KC_D, KC_R, KC_T, KC_NO, KC_NO, KC_NO, KC_Y, KC_U, KC_K, KC_L, KC_P, KC_NO, LCTL_T(KC_ESC), KC_A, KC_X, KC_C, KC_F, KC_G, KC_NO, KC_NO, KC_NO, KC_H, KC_J, OSL(3), KC_DOT, KC_SCLN, KC_NO, KC_LSFT, KC_Z, KC_NO, KC_NO, KC_V, KC_B, KC_NO, KC_NO, KC_NO, KC_N, KC_M, KC_NO, KC_NO, KC_SLSH, KC_TRNS, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_SPC, KC_BSPC, KC_NO, KC_NO, KC_LGUI, MO(14), KC_ENT, KC_RALT, KC_NO, KC_NO, KC_TRNS),
	[3] = LAYOUT_ortho_5x15(KC_NO, KC_NO, KC_AMPR, KC_QUES, KC_TILD, KC_GRV, KC_NO, KC_NO, KC_NO, KC_HASH, KC_CIRC, KC_LBRC, KC_RBRC, KC_NO, KC_NO, KC_NO, KC_PERC, KC_LPRN, KC_EQL, KC_PLUS, KC_AT, KC_NO, KC_NO, KC_NO, KC_DLR, KC_UNDS, KC_ASTR, KC_RPRN, KC_EXLM, KC_NO, KC_NO, KC_SLSH, KC_7, KC_8, KC_0, KC_LCBR, KC_NO, KC_NO, KC_NO, KC_RCBR, KC_1, KC_3, KC_4, KC_MINS, KC_DQUO, KC_NO, KC_6, KC_NO, KC_NO, KC_9, KC_PIPE, KC_NO, KC_NO, KC_NO, KC_BSLS, KC_2, KC_NO, KC_NO, KC_5, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_COMM, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS),
	[5] = LAYOUT_ortho_5x15(KC_NO, KC_NO, KC_NO, KC_NO, KC_TILD, KC_GRV, KC_NO, KC_NO, KC_NO, KC_HASH, KC_CIRC, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_PERC, KC_AMPR, KC_PLUS, KC_AT, KC_DLR, KC_NO, KC_NO, KC_NO, KC_UNDS, KC_LBRC, KC_RBRC, KC_EXLM, KC_DQUO, KC_NO, KC_NO, KC_SLSH, KC_LPRN, KC_EQL, KC_0, KC_LCBR, KC_NO, KC_NO, KC_NO, KC_RCBR, KC_1, KC_ASTR, KC_RPRN, KC_MINS, KC_NO, KC_LSFT, KC_6, KC_7, KC_8, KC_9, KC_PIPE, KC_NO, KC_NO, KC_NO, KC_BSLS, KC_2, KC_3, KC_4, KC_5, KC_RSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_COMM, KC_NO, KC_NO, KC_NO, KC_COMM, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
	[6] = LAYOUT_ortho_5x15(),
	[7] = LAYOUT_ortho_5x15(),
	[8] = LAYOUT_ortho_5x15(),
	[9] = LAYOUT_ortho_5x15(),
	[10] = LAYOUT_ortho_5x15(),
	[11] = LAYOUT_ortho_5x15(),
	[12] = LAYOUT_ortho_5x15(),
	[13] = LAYOUT_ortho_5x15(),
	[14] = LAYOUT_ortho_5x15(KC_NO, KC_ACL0, KC_ACL1, KC_ACL2, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_WH_U, KC_WH_D, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_HOME, KC_PGUP, KC_PGDN, KC_END, KC_NO, KC_NO, KC_MS_L, KC_MS_U, KC_MS_D, KC_MS_R, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LEFT, KC_UP, KC_DOWN, KC_RGHT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_BTN1, KC_BTN2, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO),
	[15] = LAYOUT_ortho_5x15(RGB_TOG, RGB_MOD, RGB_HUI, RGB_SAI, RGB_VAI, RGB_SPI, RGB_M_X, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RESET, KC_NO, RGB_RMOD, RGB_HUD, RGB_SAD, RGB_VAD, RGB_SPD, RGB_M_G, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_M_P, RGB_M_B, RGB_M_R, RGB_M_SW, RGB_M_SN, RGB_M_K, RGB_M_T, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, DF(0), DF(2), DF(4), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO)
};

